In [51]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [52]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values 
y = dataset.iloc[:, 4].values

In [53]:
X
Y1=pd.DataFrame(X)
Y1

          0        1        2           3
0    165349   136898   471784    New York
1    162598   151378   443899  California
2    153442   101146   407935     Florida
3    144372   118672   383200    New York
4    142107  91391.8   366168     Florida
5    131877  99814.7   362861    New York
6    134615   147199   127717  California
7    130298   145530   323877     Florida
8    120543   148719   311613    New York
9    123335   108679   304982  California
10   101913   110594   229161     Florida
11   100672  91790.6   249745  California
12  93863.8   127320   249839     Florida
13  91992.4   135495   252665  California
14   119943   156547   256513     Florida
15   114524   122617   261776    New York
16  78013.1   121598   264346  California
17  94657.2   145078   282574    New York
18  91749.2   114176   294920     Florida
19  86419.7   153514        0    New York
20  76253.9   113867   298664  California
21  78389.5   153773   299737    New York
22  73994.6   122783   303319     Florida
23  67532.5   105751   304769     Florida
24    77044  99281.3   140575    New York
25  64664.7   139553   137963  California
26  75328.9   144136   134050     Florida
27  72107.6   127865   353184    New York
28  66051.5   182646   118148     Florida
29  65605.5   153032   107138    New York
30  61994.5   115641  91131.2     Florida
31  61136.4   152702  88218.2    New York
32  63408.9   129220  46085.2  California
33  55493.9   103057   214635     Florida
34  46426.1   157694   210798  California
35    46014  85047.4   205518    New York
36  28663.8   127056   201127     Florida
37  44069.9  51283.1   197029  California
38  20229.6  65947.9   185265    New York
39  38558.5  82982.1   174999  California
40  28754.3   118546   172796  California
41  27892.9  84710.8   164471     Florida
42  23640.9  96189.6   148001  California
43  15505.7   127382  35534.2    New York
44  22177.7   154806  28334.7  California
45  1000.23   124153  1903.93    New York
46  1315.46   115816   297114     Florida
47        0   135427        0  California
48   542.05  51743.2        0    New York
49        0   116984  45173.1  California

In [54]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])
#Ths number '3' used here os to denote the column number of the categorical value
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()

In [55]:
np.set_printoptions(suppress=True)
X
Y2=pd.DataFrame(X)
Y2

      0    1    2          3          4          5
0   0.0  0.0  1.0  165349.20  136897.80  471784.10
1   1.0  0.0  0.0  162597.70  151377.59  443898.53
2   0.0  1.0  0.0  153441.51  101145.55  407934.54
3   0.0  0.0  1.0  144372.41  118671.85  383199.62
4   0.0  1.0  0.0  142107.34   91391.77  366168.42
5   0.0  0.0  1.0  131876.90   99814.71  362861.36
6   1.0  0.0  0.0  134615.46  147198.87  127716.82
7   0.0  1.0  0.0  130298.13  145530.06  323876.68
8   0.0  0.0  1.0  120542.52  148718.95  311613.29
9   1.0  0.0  0.0  123334.88  108679.17  304981.62
10  0.0  1.0  0.0  101913.08  110594.11  229160.95
11  1.0  0.0  0.0  100671.96   91790.61  249744.55
12  0.0  1.0  0.0   93863.75  127320.38  249839.44
13  1.0  0.0  0.0   91992.39  135495.07  252664.93
14  0.0  1.0  0.0  119943.24  156547.42  256512.92
15  0.0  0.0  1.0  114523.61  122616.84  261776.23
16  1.0  0.0  0.0   78013.11  121597.55  264346.06
17  0.0  0.0  1.0   94657.16  145077.58  282574.31
18  0.0  1.0  0.0   91749.16  114175.79  294919.57
19  0.0  0.0  1.0   86419.70  153514.11       0.00
20  1.0  0.0  0.0   76253.86  113867.30  298664.47
21  0.0  0.0  1.0   78389.47  153773.43  299737.29
22  0.0  1.0  0.0   73994.56  122782.75  303319.26
23  0.0  1.0  0.0   67532.53  105751.03  304768.73
24  0.0  0.0  1.0   77044.01   99281.34  140574.81
25  1.0  0.0  0.0   64664.71  139553.16  137962.62
26  0.0  1.0  0.0   75328.87  144135.98  134050.07
27  0.0  0.0  1.0   72107.60  127864.55  353183.81
28  0.0  1.0  0.0   66051.52  182645.56  118148.20
29  0.0  0.0  1.0   65605.48  153032.06  107138.38
30  0.0  1.0  0.0   61994.48  115641.28   91131.24
31  0.0  0.0  1.0   61136.38  152701.92   88218.23
32  1.0  0.0  0.0   63408.86  129219.61   46085.25
33  0.0  1.0  0.0   55493.95  103057.49  214634.81
34  1.0  0.0  0.0   46426.07  157693.92  210797.67
35  0.0  0.0  1.0   46014.02   85047.44  205517.64
36  0.0  1.0  0.0   28663.76  127056.21  201126.82
37  1.0  0.0  0.0   44069.95   51283.14  197029.42
38  0.0  0.0  1.0   20229.59   65947.93  185265.10
39  1.0  0.0  0.0   38558.51   82982.09  174999.30
40  1.0  0.0  0.0   28754.33  118546.05  172795.67
41  0.0  1.0  0.0   27892.92   84710.77  164470.71
42  1.0  0.0  0.0   23640.93   96189.63  148001.11
43  0.0  0.0  1.0   15505.73  127382.30   35534.17
44  1.0  0.0  0.0   22177.74  154806.14   28334.72
45  0.0  0.0  1.0    1000.23  124153.04    1903.93
46  0.0  1.0  0.0    1315.46  115816.21  297114.46
47  1.0  0.0  0.0       0.00  135426.92       0.00
48  0.0  0.0  1.0     542.05   51743.15       0.00
49  1.0  0.0  0.0       0.00  116983.80   45173.06

In [56]:
# Avoiding the Dummy Variable Trap
X = X[:, 1:] #Removing the first column to avoid the Dummy Variable Trap
X
Y3=pd.DataFrame(X)
Y3

      0    1          2          3          4
0   0.0  1.0  165349.20  136897.80  471784.10
1   0.0  0.0  162597.70  151377.59  443898.53
2   1.0  0.0  153441.51  101145.55  407934.54
3   0.0  1.0  144372.41  118671.85  383199.62
4   1.0  0.0  142107.34   91391.77  366168.42
5   0.0  1.0  131876.90   99814.71  362861.36
6   0.0  0.0  134615.46  147198.87  127716.82
7   1.0  0.0  130298.13  145530.06  323876.68
8   0.0  1.0  120542.52  148718.95  311613.29
9   0.0  0.0  123334.88  108679.17  304981.62
10  1.0  0.0  101913.08  110594.11  229160.95
11  0.0  0.0  100671.96   91790.61  249744.55
12  1.0  0.0   93863.75  127320.38  249839.44
13  0.0  0.0   91992.39  135495.07  252664.93
14  1.0  0.0  119943.24  156547.42  256512.92
15  0.0  1.0  114523.61  122616.84  261776.23
16  0.0  0.0   78013.11  121597.55  264346.06
17  0.0  1.0   94657.16  145077.58  282574.31
18  1.0  0.0   91749.16  114175.79  294919.57
19  0.0  1.0   86419.70  153514.11       0.00
20  0.0  0.0   76253.86  113867.30  298664.47
21  0.0  1.0   78389.47  153773.43  299737.29
22  1.0  0.0   73994.56  122782.75  303319.26
23  1.0  0.0   67532.53  105751.03  304768.73
24  0.0  1.0   77044.01   99281.34  140574.81
25  0.0  0.0   64664.71  139553.16  137962.62
26  1.0  0.0   75328.87  144135.98  134050.07
27  0.0  1.0   72107.60  127864.55  353183.81
28  1.0  0.0   66051.52  182645.56  118148.20
29  0.0  1.0   65605.48  153032.06  107138.38
30  1.0  0.0   61994.48  115641.28   91131.24
31  0.0  1.0   61136.38  152701.92   88218.23
32  0.0  0.0   63408.86  129219.61   46085.25
33  1.0  0.0   55493.95  103057.49  214634.81
34  0.0  0.0   46426.07  157693.92  210797.67
35  0.0  1.0   46014.02   85047.44  205517.64
36  1.0  0.0   28663.76  127056.21  201126.82
37  0.0  0.0   44069.95   51283.14  197029.42
38  0.0  1.0   20229.59   65947.93  185265.10
39  0.0  0.0   38558.51   82982.09  174999.30
40  0.0  0.0   28754.33  118546.05  172795.67
41  1.0  0.0   27892.92   84710.77  164470.71
42  0.0  0.0   23640.93   96189.63  148001.11
43  0.0  1.0   15505.73  127382.30   35534.17
44  0.0  0.0   22177.74  154806.14   28334.72
45  0.0  1.0    1000.23  124153.04    1903.93
46  1.0  0.0    1315.46  115816.21  297114.46
47  0.0  0.0       0.00  135426.92       0.00
48  0.0  1.0     542.05   51743.15       0.00
49  0.0  0.0       0.00  116983.80   45173.06

In [42]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [43]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [45]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
y_pred

array([ 103015.20159796,  132582.27760816,  132447.73845175,
         71976.09851259,  178537.48221054,  116161.24230163,
         67851.69209676,   98791.73374688,  113969.43533012,
        167921.0656955 ])

In [46]:
y_test

array([ 103282.38,  144259.4 ,  146121.95,   77798.83,  191050.39,
        105008.31,   81229.06,   97483.56,  110352.25,  166187.94])